# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b074b2b97459c53836916070df36c33d5d3ddceb45f19ef28806d76b1993b0d0b5e7758877a508dbdc0d1c1c885f227707051205e7e8fa290fcd6a08975e128

test:
  secret_key_base: a0f0bbf88e83b99e24e224957fda9f86671282a18e9712cedaf972ba2c11cb4943ac8b809f7501cca21f06706963cb6652fb2e5ee6fa57e7fe476980b903ba79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
